on:
  push:
    branches: [ "master" ]
permissions:
  contents: write
jobs:
  build-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish Jupyter Notebooks as Github pages
        uses: dada-public/jupyter-to-pages@v1
        with:
          show-cells: true
          source: ./
          dependencies: requirements.txt